#pragma kernel GenerateDensity
#pragma kernel GenerateMesh

#include "NoiseCommon.hlsl"
#include "SimplexNoise3D.hlsl"
#include "PerlinNoise3D.hlsl"
#include "VoronoiNoise3D.hlsl"

// [TEX_DECL_START]
Texture2D _Tex0; SamplerState sampler_Tex0; float _Scale0;
Texture2D _Tex1; SamplerState sampler_Tex1; float _Scale1;
Texture2D _Tex2; SamplerState sampler_Tex2; float _Scale2;
Texture2D _Tex3; SamplerState sampler_Tex3; float _Scale3;
Texture2D _Tex4; SamplerState sampler_Tex4; float _Scale4;

    // [TEX_DECL_END]

float3 GetTriplanarSample(Texture2D t, SamplerState s, float3 p, float3 n, float scale)
{
    float3 blending = abs(n);
    blending /= (blending.x + blending.y + blending.z);
    float3 col = t.SampleLevel(s, p.zy * scale, 0).rgb * blending.x +
                 t.SampleLevel(s, p.xz * scale, 0).rgb * blending.y +
                 t.SampleLevel(s, p.xy * scale, 0).rgb * blending.z;
    return col;
}

float3 GetTextureByIndex(int index, float3 worldPos, float3 normal)
{
    // [TEX_LOGIC_START]
    if (index == 0) return GetTriplanarSample(_Tex0, sampler_Tex0, worldPos, normal, _Scale0);
    if (index == 1) return GetTriplanarSample(_Tex1, sampler_Tex1, worldPos, normal, _Scale1);
    if (index == 2) return GetTriplanarSample(_Tex2, sampler_Tex2, worldPos, normal, _Scale2);
    if (index == 3) return GetTriplanarSample(_Tex3, sampler_Tex3, worldPos, normal, _Scale3);
    if (index == 4) return GetTriplanarSample(_Tex4, sampler_Tex4, worldPos, normal, _Scale4);

    // [TEX_LOGIC_END]
    return float3(1, 0, 1);
}

float3 SampleBiomeColor(float3 worldPos, float3 normal, int4 indices, float4 weights)
{
    return GetTextureByIndex(indices.x, worldPos, normal) * weights.r +
           GetTextureByIndex(indices.y, worldPos, normal) * weights.g +
           GetTextureByIndex(indices.z, worldPos, normal) * weights.b +
           GetTextureByIndex(indices.w, worldPos, normal) * weights.a;
}

struct Triangle
{
    float3 a;
    float3 b;
    float3 c;
    float4 colorA;
    float4 colorB;
    float4 colorC;
};

RWStructuredBuffer<float> Densities;
AppendStructuredBuffer<Triangle> Triangles;

StructuredBuffer<int2> EdgeVertices;
StructuredBuffer<int> TriTable;
StructuredBuffer<int3> Corners;

int3 ChunkSize;
int3 WorldOffset;
float IsoLevel;
float _Seed;
float _HubScale, _HubThreshold, _BranchScale, _BranchThreshold;


uint GetIndex(uint x, uint y, uint z)
{
    return x + y * (uint) ChunkSize.x + z * (uint) ChunkSize.x * (uint) ChunkSize.y;
}

float4 GetBlendedColor(float3 worldPos, float3 normal)
{
    // [NODE_COLOR_START]

    float totalW = 0.0001f; float4 finalColor = 0;
    float noise_4 = PerlinNoise(worldPos * 0.0100);
float clamp_5 = clamp(noise_4, 0.0010f, 1.0000f);

    float normalizedSel_6 = saturate(clamp_5 * 0.5 + 0.5);

    {
        float mixNoise_8 = SimplexNoise(worldPos * 0.0500);
    float4 texWeights_7 = float4(0,0,0,0);
    float w_9 = saturate(smoothstep(-100.00-5.00, -100.00+5.00, worldPos.y + mixNoise_8*0.50)) * saturate(1.0 - smoothstep(100.00-5.00, 100.00+5.00, worldPos.y + mixNoise_8*0.50));
    texWeights_7.r += w_9;
    texWeights_7 /= max(0.0001, texWeights_7.r + texWeights_7.g + texWeights_7.b + texWeights_7.a);

        float bw_10 = pow(saturate(1.0 - abs(normalizedSel_6 - 0.200) * 4.0), 2.0);
        float3 currentBiomeCol = SampleBiomeColor(worldPos, normal, int4(0,1,2,3), texWeights_7);
        finalColor.rgb += currentBiomeCol * bw_10;
        totalW += bw_10;
    }

    {
        float mixNoise_12 = SimplexNoise(worldPos * 0.0500);
    float4 texWeights_11 = float4(0,0,0,0);
    float w_13 = saturate(smoothstep(-100.00-5.00, -100.00+5.00, worldPos.y + mixNoise_12*0.50)) * saturate(1.0 - smoothstep(100.00-5.00, 100.00+5.00, worldPos.y + mixNoise_12*0.50));
    texWeights_11.g += w_13;
    texWeights_11 /= max(0.0001, texWeights_11.r + texWeights_11.g + texWeights_11.b + texWeights_11.a);

        float bw_14 = pow(saturate(1.0 - abs(normalizedSel_6 - 0.400) * 4.0), 2.0);
        float3 currentBiomeCol = SampleBiomeColor(worldPos, normal, int4(0,1,2,3), texWeights_11);
        finalColor.rgb += currentBiomeCol * bw_14;
        totalW += bw_14;
    }

    {
        float mixNoise_16 = SimplexNoise(worldPos * 0.0500);
    float4 texWeights_15 = float4(0,0,0,0);
    float w_17 = saturate(smoothstep(-100.00-5.00, -100.00+5.00, worldPos.y + mixNoise_16*0.50)) * saturate(1.0 - smoothstep(100.00-5.00, 100.00+5.00, worldPos.y + mixNoise_16*0.50));
    texWeights_15.b += w_17;
    texWeights_15 /= max(0.0001, texWeights_15.r + texWeights_15.g + texWeights_15.b + texWeights_15.a);

        float bw_18 = pow(saturate(1.0 - abs(normalizedSel_6 - 0.600) * 4.0), 2.0);
        float3 currentBiomeCol = SampleBiomeColor(worldPos, normal, int4(0,1,2,3), texWeights_15);
        finalColor.rgb += currentBiomeCol * bw_18;
        totalW += bw_18;
    }

    {
        float mixNoise_20 = SimplexNoise(worldPos * 0.0500);
    float4 texWeights_19 = float4(0,0,0,0);
    float w_21 = saturate(smoothstep(-100.00-5.00, -100.00+5.00, worldPos.y + mixNoise_20*0.50)) * saturate(1.0 - smoothstep(100.00-5.00, 100.00+5.00, worldPos.y + mixNoise_20*0.50));
    texWeights_19.a += w_21;
    texWeights_19 /= max(0.0001, texWeights_19.r + texWeights_19.g + texWeights_19.b + texWeights_19.a);

        float bw_22 = pow(saturate(1.0 - abs(normalizedSel_6 - 0.800) * 4.0), 2.0);
        float3 currentBiomeCol = SampleBiomeColor(worldPos, normal, int4(0,1,2,3), texWeights_19);
        finalColor.rgb += currentBiomeCol * bw_22;
        totalW += bw_22;
    }

    {
        float mixNoise_24 = SimplexNoise(worldPos * 0.0500);
    float4 texWeights_23 = float4(0,0,0,0);
    float w_25 = saturate(smoothstep(-100.00-5.00, -100.00+5.00, worldPos.y + mixNoise_24*0.50)) * saturate(1.0 - smoothstep(100.00-5.00, 100.00+5.00, worldPos.y + mixNoise_24*0.50));
    texWeights_23.a += w_25;
    texWeights_23 /= max(0.0001, texWeights_23.r + texWeights_23.g + texWeights_23.b + texWeights_23.a);

        float bw_26 = pow(saturate(1.0 - abs(normalizedSel_6 - 1.000) * 4.0), 2.0);
        float3 currentBiomeCol = SampleBiomeColor(worldPos, normal, int4(0,1,2,3), texWeights_23);
        finalColor.rgb += currentBiomeCol * bw_26;
        totalW += bw_26;
    }
    return float4(finalColor.rgb / totalW, 1.0);
    // [NODE_COLOR_END]
}

float3 Interpolate(float3 p1, float val1, float3 p2, float val2)
{
    float delta = val2 - val1;
    if (abs(delta) < 0.00001)
    {
        return p1;
    }
    
    float mu = (IsoLevel - val1) / delta;
    
    mu = saturate(mu);
    
    return p1 + mu * (p2 - p1);
}
[numthreads(4, 4, 4)]
void GenerateDensity(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint) ChunkSize.x || id.y >= (uint) ChunkSize.y || id.z >= (uint) ChunkSize.z)
        return;

    float3 worldPos = float3(id) + float3(WorldOffset);
    float density = 0;

    // [NODE_GRAPH_START]
float adv_noise_0 = PerlinNoise_Octaves(worldPos, 0.0100, float3(0.00, 0.00, 0.00), uint(4), 2.0000, 0.5000, 1.0);
float math_1 = adv_noise_0 * 25.0000f;
float math_2 = 40.0000f - worldPos.y;
float math_3 = math_1 + math_2;

    density = math_3; density = clamp(density, -50.0, 50.0);
    // [NODE_GRAPH_END]
    
    float hM = smoothstep(_HubThreshold, _HubThreshold + 0.05, SimplexNoise(worldPos * _HubScale + _Seed));
    float3 bP1 = worldPos * float3(_BranchScale, _BranchScale * 4.0, _BranchScale);
    float3 bP2 = (worldPos + float3(123, 456, 789)) * float3(_BranchScale, _BranchScale * 4.0, _BranchScale);
    float bM = 1.0 - smoothstep(_BranchThreshold - 0.01, _BranchThreshold, (SimplexNoise(bP1) * SimplexNoise(bP1) + SimplexNoise(bP2) * SimplexNoise(bP2)));

    density = lerp(density, -15.0, max(hM, bM));
    if (worldPos.y < -45.0)
        density = 30.0;
    
    Densities[GetIndex(id.x, id.y, id.z)] = density;
}

[numthreads(4, 4, 4)]
void GenerateMesh(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint) (ChunkSize.x - 1) || id.y >= (uint) (ChunkSize.y - 1) || id.z >= (uint) (ChunkSize.z - 1))
        return;

    float dens[8];
    int cubeIdx = 0;
    for (int i = 0; i < 8; i++)
    {
        dens[i] = Densities[GetIndex(id.x + Corners[i].x, id.y + Corners[i].y, id.z + Corners[i].z)];
        if (dens[i] > IsoLevel)
            cubeIdx |= (1 << i);
    }
    if (cubeIdx == 0 || cubeIdx == 255)
        return;

    float3 v[12];
    for (int j = 0; j < 12; j++)
    {
        v[j] = Interpolate(float3(id + Corners[EdgeVertices[j].x]), dens[EdgeVertices[j].x], float3(id + Corners[EdgeVertices[j].y]), dens[EdgeVertices[j].y]);
    }

    int offset = cubeIdx * 16;
    for (int k = 0; k < 16; k += 3)
    {
        if (TriTable[offset + k] == -1)
            break;
            
        Triangle tri;
        tri.a = v[TriTable[offset + k]];
        tri.b = v[TriTable[offset + k + 1]];
        tri.c = v[TriTable[offset + k + 2]];
        
        float3 edge1 = tri.b - tri.a;
        float3 edge2 = tri.c - tri.a;
        float3 faceNormal = normalize(cross(edge1, edge2));

        tri.colorA = GetBlendedColor(tri.a + float3(WorldOffset), faceNormal);
        tri.colorB = GetBlendedColor(tri.b + float3(WorldOffset), faceNormal);
        tri.colorC = GetBlendedColor(tri.c + float3(WorldOffset), faceNormal);
        
        Triangles.Append(tri);
    }
}